name: Release Stable
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [11]
        # and run on both Linux and Windows
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previous-tag
        uses: WyriHaximus/github-action-get-previous-tag@1.0.0
      - name: Create version tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            let oldTag = "${{ steps.previous-tag.outputs.tag }}"
            let regex = /[v]?([0-9]+\.[0-9]+\.[0-9]+)+-beta.([0-9]+)[+]?.*/
            if (regex.test(oldTag)) {
              let match = oldTag.match(regex)
              let betaIncrement = parseInt(match[2], 10) + 1
              github.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "refs/tags/v" + match[1],
                sha: context.sha
              })
            }
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew buildAndAttemptRelease publishToMavenLocal --stacktrace --parallel
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '11' }} # Only upload artifacts built from LTS java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
